# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pictorlabs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'get_latest_by': 'last_modified', 'ordering': ['last_modified']},
        ),
        migrations.AddField(
            model_name='entity',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pictorlabs.Entity'),
        ),
    ]
