# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 00:04
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pictorlabs', '0002_auto_20160912_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='title',
            field=models.TextField(blank=True, db_index=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='doc',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pictorlabs.Entity'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='url',
            field=models.TextField(db_index=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='entity',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
