# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictorlabs', '0004_entity_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='image_url',
            field=models.TextField(blank=True, db_index=True, max_length=2048, null=True),
        ),
    ]
